# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tobaccno' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for tobaccno
	pod 'Realm'
    pod 'AFNetworking'
    pod 'ABVolumeControl'
    pod 'ABUtils'
    pod 'ABKeyboardAccessory'
    pod 'ABMediaView'

end
